# Generated by Django 5.0.6 on 2024-05-19 12:13

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='cafedra',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cafedra',
            name='image',
            field=models.ImageField(upload_to='images/cafedras/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='cafedra',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='mysite.teacher', verbose_name='Преподаватели'),
        ),
        migrations.AlterField(
            model_name='cafedra',
            name='title',
            field=models.CharField(max_length=123, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=123, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='news',
            name='views',
            field=models.IntegerField(blank=True, null=True, verbose_name='Колличество просмотров'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='address',
            field=models.CharField(max_length=123, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contacts',
            field=models.TextField(blank=True, verbose_name='Контакт'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='dictors',
            field=models.ManyToManyField(blank=True, to='mysite.teacher', verbose_name='Директорат'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='emails',
            field=models.TextField(blank=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='education',
            field=models.TextField(blank=True, null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='exp',
            field=models.CharField(blank=True, max_length=123, null=True, verbose_name='Опыт в годах'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/teachers/', verbose_name='Изоюражение'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_manage',
            field=models.BooleanField(blank=True, default=False, verbose_name='Директорат'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=123, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=134, null=True, verbose_name='Номер Телефона'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profession',
            field=models.CharField(max_length=123, verbose_name='Профессия'),
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mysite.category'),
        ),
    ]
