# Generated by Django 5.0.6 on 2024-06-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_sitesetting_address_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.CharField(max_length=123, verbose_name='Почта'),
        ),
    ]
