# Generated by Django 5.0.6 on 2024-06-03 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_alter_application_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafedra',
            options={'ordering': ['title'], 'verbose_name': 'Направления', 'verbose_name_plural': 'Направлении'},
        ),
    ]
