# Generated by Django 5.0.6 on 2024-06-03 13:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_alter_cafedra_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='О нас'),
        ),
    ]
