# Generated by Django 5.0.6 on 2024-06-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_remove_pagefile_image_pagefile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagefile',
            name='description',
            field=models.CharField(default=1, max_length=123),
            preserve_default=False,
        ),
    ]
