# Generated by Django 5.0.6 on 2024-06-10 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_pagefile_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Категория для страниц',
                'verbose_name_plural': 'Категории для страниц',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mysite.categorypage', verbose_name='категория'),
            preserve_default=False,
        ),
    ]
